//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisESport.fr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class paris_user
    {
        public int Id { get; set; }
        public int user_id { get; set; }
        public int match_id { get; set; }
        public int resultat_parie { get; set; }
        public double credit_parie { get; set; }
    
        public virtual Matchs Matchs { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
