//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisESport.fr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournois
    {
        public Tournois()
        {
            this.Matchs = new HashSet<Matchs>();
            this.Equipes = new HashSet<Equipes>();
        }
    
        public int Id { get; set; }
        public string nom { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
        public int jeu_id { get; set; }
    
        public virtual Jeux Jeux { get; set; }
        public virtual ICollection<Matchs> Matchs { get; set; }
        public virtual ICollection<Equipes> Equipes { get; set; }
    }
}
