//------------------------------------------------------------------------------
// <auto-generated>
//    Ce code a été généré à partir d'un modèle.
//
//    Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//    Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParisESport.fr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_infos
    {
        public int Id { get; set; }
        public string mail { get; set; }
        public double credits { get; set; }
        public int UserId { get; set; }
        public bool admin { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
    }
}
